Code refactoring

diff --git a/scripts/nitro-pipe b/scripts/nitro-pipe
--- a/scripts/nitro-pipe
+++ b/scripts/nitro-pipe
@@ -1,4 +1,18 @@
 #!/bin/bash
+eval export CONTEXT_ENV_B64=$NITRO_PIPELINES_BUILD_ENV_FILE
+filename=$(uuidgen)
+echo $CONTEXT_ENV_B64 | base64 --decode >> ./$filename.tmp && envsubst < ./$filename.tmp > ./$filename.env && rm ./$filename.tmp
+if [ -s ./$filename.env  ]; then
+	source ./$filename.env && export $(cut -d= -f1 ./$filename.env)
+else
+	echo "File ./$filename.env is empty"
+    exit 1
+fi
+rm -f ./$filename.env
+if [ -z "$1" ]; then
+    echo "No required arguments supplied (operation=any|build|deploy, ms_name)."
+    exit 1
+fi
 cwd=$(dirname "$0")
 ./nitro $1 $2
 if [[ $? -ne 0 ]]; then exit 1;fi
